### ISSUE TITLE
Error with `verilator@5.046.bcr.2`

### ISSUE THREAD

**Issue by MrAMS** [MrAMS/bazel_rules_verilator#11]
`rules_verilator@0.3.1` do not work with newest `verilator@5.046.bcr.2`

related https://github.com/The-OpenROAD-Project/bazel-orfs/pull/664 and https://github.com/The-OpenROAD-Project/bazel-orfs/pull/661#issuecomment-4208254784

logs:

```
❯ bazel test //...
FAIL: //.bcr/tools/bzl_version:version_test (see /home/yqj/.cache/bazel/_bazel_yqj/8a37cd9d1b0731cec72ab70ac130a1a1/execroot/_main/bazel-out/k8-fastbuild/testlogs/.bcr/tools/bzl_version/version_test/test.log)
INFO: Analyzed 33 targets (569 packages loaded, 7120 targets configured).
ERROR: /home/yqj/.cache/bazel/_bazel_yqj/8a37cd9d1b0731cec72ab70ac130a1a1/external/bison~/BUILD.bazel:974:11: Compiling src/bazel_runfiles.cc [for tool] failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@bison~//:bison_bazel_runfiles) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 28 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/bison~/src/bazel_runfiles.cc: In function 'void bazel_runfiles_init(const char*)':
external/bison~/src/bazel_runfiles.cc:33:35: error: 'BAZEL_CURRENT_REPOSITORY' was not declared in this scope
   33 |     std::string source_repository(BAZEL_CURRENT_REPOSITORY);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/yqj/.cache/bazel/_bazel_yqj/8a37cd9d1b0731cec72ab70ac130a1a1/external/verilator~/BUILD.bazel:232:11 Compiling external/verilator~/V3Const__gen.cpp [for tool] failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@bison~//:bison_bazel_runfiles) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 28 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 35.222s, Critical Path: 2.02s
INFO: 3806 processes: 3788 internal, 18 linux-sandbox.
ERROR: Build did NOT complete successfully
//verilator/tests:adder_test                                          NO STATUS
//verilator/tests:adder_trace_test                                    NO STATUS
//verilator/tests:hierarchical_compile_test                           NO STATUS
//verilator/tests:include_top_test                                    NO STATUS
//verilator/tests:load_and_count_test                                 NO STATUS
//verilator/tests:nested_module_test                                  NO STATUS
//.bcr/tools/bzl_version:version_test                                    FAILED in 0.6s
  /home/yqj/.cache/bazel/_bazel_yqj/8a37cd9d1b0731cec72ab70ac130a1a1/execroot/_main/bazel-out/k8-fastbuild/testlogs/.bcr/tools/bzl_version/version_test/test.log

Executed 1 out of 7 tests: 1 fails locally and 6 were skipped.
❯ bazel test //...
INFO: Analyzed 33 targets (0 packages loaded, 0 targets configured).
ERROR: /home/yqj/.cache/bazel/_bazel_yqj/8a37cd9d1b0731cec72ab70ac130a1a1/external/bison~/BUILD.bazel:974:11: Compiling src/bazel_runfiles.cc [for tool] failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@bison~//:bison_bazel_runfiles) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 28 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/bison~/src/bazel_runfiles.cc: In function 'void bazel_runfiles_init(const char*)':
external/bison~/src/bazel_runfiles.cc:33:35: error: 'BAZEL_CURRENT_REPOSITORY' was not declared in this scope
   33 |     std::string source_repository(BAZEL_CURRENT_REPOSITORY);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/yqj/proj/buildtools/bazel_rules_verilator/verilator/tests/BUILD:70:8 Compiling verilator/tests/adder_test.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@bison~//:bison_bazel_runfiles) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 28 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 1.693s, Critical Path: 1.08s
INFO: 381 processes: 381 internal.
ERROR: Build did NOT complete successfully
//.bcr/tools/bzl_version:version_test                                 NO STATUS
//verilator/tests:adder_trace_test                                    NO STATUS
//verilator/tests:hierarchical_compile_test                           NO STATUS
//verilator/tests:include_top_test                                    NO STATUS
//verilator/tests:load_and_count_test                                 NO STATUS
//verilator/tests:nested_module_test                                  NO STATUS
//verilator/tests:adder_test                                    FAILED TO BUILD

Executed 0 out of 7 tests: 1 fails to build and 6 were skipped.
```

**Comment by MrAMS** [comment]
@UebelAndre Is there something wrong with `bison` related to `verilator@5.046.bcr.2` ?

**Comment by MrAMS** [comment]
It seems that `verilator@5.046.bcr.2` has a refactor, I am working on a new version of rules_verilator to fit in new version of verilator.

**Comment by UebelAndre** [comment]
Hey! Yeah, I did a deep dive into how verilator is built with it's original CMakeLists and restructured it to match as 1-1 as I could. https://github.com/hw-bzl/rules_verilator/pull/10 was working with the newest version if you need an example but for the most part I don't remember it being to terribly different. I thought bison and verilator are tested across Bazel 7, 8, and 9
bison: https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/bison/3.8.2.bcr.5/presubmit.yml
verilator: https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/verilator/5.046/presubmit.yml

I'm curious what I missed in setting up the test matrix

**Comment by UebelAndre** [comment]
If the naming is incorrect I'm happy to update it. The runtime name seems kinda elusive as there's no CMake target for. I *thought* it was `verilated` based on `verilated.h` but if that's wrong I will update. Just let me know!

**Comment by MrAMS** [comment]
The error error: 'BAZEL_CURRENT_REPOSITORY' was not declared in this scope is caused by an outdated Bazel version. Upgrading .bazelversion to 8.6.0 resolves this issue.
However, we are now encountering another problem related to a bug in `m4@1.4.20.bcr.4` on `glibc 2.43 / GCC 15`.

---

@UebelAndre Hi, I found that `verilator@5.046.bcr.2` use `m4@1.4.20.bcr.4` which has bug on `glibc 2.43 / GCC 15` (see https://www.mail-archive.com/debian-bugs-dist%40lists.debian.org/msg2082307.html https://www.mail-archive.com/debian-bugs-dist%40lists.debian.org/msg2083261.html https://www.mail-archive.com/debian-bugs-closed%40lists.debian.org/msg829792.html), maybe we should upgrade to `m4@1.4.21` (see https://lists.gnu.org/archive/html/info-gnu/2026-01/msg00005.html)

**Comment by MrAMS** [comment]
@UebelAndre  Oh, it looks like m4@1.4.21 isn’t available on BCR yet 😢 As the maintainer of m4, would you mind publishing m4@1.4.21 when you have a chance?

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/8358 waiting on the mirror request to be approved

**Comment by MrAMS** [comment]
@UebelAndre `m4@1.4.21` works well! 🥳 Could you please release a `verilator@5.046.bcr.3` or something to upgrade `m4` at your convenience? Thank you 😃

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/8380

**Comment by MrAMS** [comment]
Great! `rules_verilator@0.3.2` now support `verilator@5.046.bcr.3` 🥳 
related: https://github.com/bazelbuild/bazel-central-registry/pull/8384
